services:
  web:
    build: .
    ports:
      - '3000:3000'
  db:
    image: 'postgres'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
