version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build-api:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: Install Node Modules
          command: |
            yarn install
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Unit Tests
          command: |
            yarn test

workflows:
  dev:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
  run-npm-command:
    jobs:
      - build-api
# yarn lint
# yarn test
# docker-compose build
# docker-compose up
# integration tests
