version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version

workflows:
  dev:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
  run-npm-command:
    jobs:
      - install-node
      - node/run:
          yarn-run: lint
      - node/run:
          yarn-run: test
# yarn lint
# yarn test
# docker-compose build
# docker-compose up
# integration tests
